import type { Metadata } from "next";
import RootLayout from "@/components/RootLayout";
import 'font-awesome/css/font-awesome.min.css';


export const metadata: Metadata = {
  title: "LRV",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.png",
  },
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <RootLayout>{children}</RootLayout>;
}
